import React from "react";
import styled from "styled-components";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import thumb from "../../public/weather.png";
import Image from "next/image";
import {
  javascriptLoader,
  reactLoader,
  cssLoader,
} from "../../components/loader";

const MainContainer = styled.main`
  min-width: 100vw;
  min-height: 100vh;
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  padding-left: 20%;
  padding-right: 20%;
  padding-top: 1rem;
  .description-container {
    font-size: 25px;
    font-family: DM Sans;
    color: white;
    a {
      color: white;
    }
    .details {
      margin-top: 1rem;
    }
    .stack {
      display: flex;
      height: 100px;
      margin-top: 1rem;
      margin-top: 1rem;
      a {
        margin-left: 1rem;
        margin-right: 1rem;
      }
    }
  }
  @media (max-width: 650px) {
    padding-left: 12%;
    padding-right: 12%;
  }
`;

const Title = styled.h1`
  font-size: 45px;
  font-family: DM Sans;
  font-weight: 600;
  color: white;
  margin-bottom: 3rem;
  margin-top: 3rem;
`;

export default function paletter() {
  return (
    <div
      style={{
        backgroundImage: "linear-gradient(to right, #222222 0%, black 100%)",
      }}
    >
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainContainer>
        <Image src={thumb} alt="thumbnail paletter" />
        <Title>Weather</Title>
        <div className="description-container">
          <p>
            Aplicativo React que mostra a temperatura no seu local através da
            geolocalização do browser.
          </p>
          <p className="details">
            Website:{" "}
            <a href="https://nardi00.github.io/react-weather-app/">
              https://nardi00.github.io/react-weather-app/
            </a>
          </p>
          <p className="details">Plataforma: Web </p>
          <div>
            <p className="details">Stack: </p>
            <div className="stack">
              <a>
                <Image
                  className="icon"
                  loader={javascriptLoader}
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
                  alt="javascript"
                  width={40}
                  height={40}
                />
              </a>
              <a>
                <Image
                  className="icon"
                  loader={reactLoader}
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
                  alt="react"
                  width={40}
                  height={40}
                />
              </a>
              <a>
                <Image
                  className="icon"
                  loader={cssLoader}
                  src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
                  alt="css"
                  width={40}
                  height={40}
                />
              </a>
            </div>
          </div>
        </div>
      </MainContainer>
    </div>
  );
}
