import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  return (
    <Screen>
      <Head>
        <title>Guilherme Nardi - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Links>icons</Links>
        <Contact>Contact</Contact>
      </Header>

      <MainContainer>
        <Main>
          <Title>/GUILHERME NARDI</Title>
          <Description>
          Front-end developer based in São Paulo, Brazil
          </Description>
          <Nav>
          <Button>Sobre</Button>
          <Button>Projetos</Button>
          </Nav>
        </Main>
      </MainContainer>


    </Screen>
  );
}

const Screen = styled.div`
  min-width: 100vw;
  min-height: 100vh;
  background-image: linear-gradient(to right, #222222 0%, black 100%);
  overflow: hidden;
  display: flex;
  flex-flow: column;
`;

const Header = styled.div`
  min-width: 100%;
  height: 100px;
  display: flex;
  justify-content: space-between;
  padding-left: 5rem;
  padding-right: 5rem;
  align-items: center;
`;
const Links = styled.div`
  width: 200px;
  color: white;
`;

const Contact = styled.button`
  cursor: pointer;
  background-color: #111111;
  border: 1px solid white;
  border-radius: 5px;
  font-family: DM Sans;
  font-size: 18px;
  color: white;
  padding: 0.5rem;
  transition: 0.5s;
  &:hover{
    color: red;
  }
`;

const MainContainer = styled.main`
  min-width: 100%;
  min-height: 100%;
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
`

const Main = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const Title = styled.h1`
  font-size: 60px;
  font-family: DM Mono;
  font-weight: 600;
  color: white;
`
const Description = styled.div`
  width: 100%;
  font-family: DM Sans;
  font-weight: 600;
  margin-top: 1rem;
  font-size: 40px;
  color: white;
`

const Nav = styled.div`
  width: 50%;
  padding-left: 1rem;
  padding-right: 1rem;
  display: flex;
  justify-content: space-between;
  margin-top: 8rem;
`

const Button = styled.button`
  font-family: DM Sans;
  font-weight: 600;
  font-size: 30px;
  color: white;
  background: none;
  cursor: pointer;
  transition: 0.5s;
  &:hover{
    color: red;
  }
`