import Head from "next/head";
import styled from "styled-components";
import Link from "next/link";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import GitHubIcon from "@mui/icons-material/GitHub";

export default function Home() {
  return (
    <Screen>
      <Head>
        <title>Guilherme Nardi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Links><a href="https://www.linkedin.com/in/guilherme-nardi-7a3406217/" >
          <LinkedInIcon fontSize="medium" />
        </a>
        <a href="https://github.com/nardi00" >
          <GitHubIcon fontSize="medium" />
        </a></Links>
        <Contact>
          <a
            href="mailto:guilhermenardi3@outlook.com"
            style={{ textDecoration: "none", color: "white", transition: "0.5s"}}
          >
            Contato
          </a>
        </Contact>
      </Header>

      <MainContainer>
        <Main>
          <Title>/GUILHERME NARDI</Title>
          <Description>
            Front-end developer based in <strong>São Paulo, Brazil</strong>
          </Description>
          <Nav>
            <Link href="/sobre" passHref>
              <Button>Sobre</Button>
            </Link>
            <Link href="/projetos" passHref>
              <Button>Projetos</Button>
            </Link>
          </Nav>
        </Main>
      </MainContainer>
    </Screen>
  );
}

const Screen = styled.div`
  min-width: 100vw;
  min-height: 100vh;
  background-image: linear-gradient(to right, #222222 0%, black 100%);
  overflow: hidden;
  display: flex;
  flex-flow: column;
`;

const Header = styled.div`
  min-width: 100%;
  height: 100px;
  display: flex;
  justify-content: space-between;
  padding-left: 5rem;
  padding-right: 5rem;
  align-items: center;
`;
const Links = styled.div`
  width: 200px;
  color: white;
  & > a {
    margin-left: 1em;
    margin-right: 1em;
    cursor: pointer;
    color: white;
  }
`;

const Contact = styled.button`
  cursor: pointer;
  background-color: #111111;
  border: 1px solid white;
  border-radius: 5px;
  font-family: DM Sans;
  font-size: 18px;
  color: white;
  padding: 0.5rem;
  transition: 0.5s;
  background: none;
  &:hover {
    color: red;
  }
  @media (max-width: 650px) {
    font-size: 15px;
  }
`;

const MainContainer = styled.main`
  min-width: 100%;
  min-height: 100%;
  flex-grow: 1;
  display: flex;
  align-items: center;
  justify-content: center;
`;

const Main = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
const Title = styled.h1`
  font-size: 60px;
  font-family: DM Mono;
  font-weight: 600;
  color: white;

  @media (max-width: 940px) {
    font-size: 45px;
  }
  @media (max-width: 560px) {
    font-size: 35px;
  }
`;
const Description = styled.div`
  width: 100%;
  font-family: DM Sans;
  font-weight: 600;
  margin-top: 1rem;
  font-size: 40px;
  color: white;
  & > strong {
    color: red;
  }
  @media (max-width: 940px) {
    font-size: 30px;
  }
  @media (max-width: 660px) {
    font-size: 22px;
  }
`;

const Nav = styled.div`
  width: 40%;
  padding-left: 1rem;
  padding-right: 1rem;
  display: flex;
  justify-content: space-between;
  margin-top: 8rem;
  @media (max-width: 660px) {
    padding-left: 0;
    padding-right: 0;
  }
`;

const Button = styled.button`
  font-family: DM Sans;
  font-weight: 600;
  font-size: 30px;
  color: white;
  background: none;
  cursor: pointer;
  transition: 0.5s;
  padding: 0.5rem;
  border: none;
  &:hover {
    color: red;
  }
  @media (max-width: 940px) {
    font-size: 25px;
  }
  @media (max-width: 660px) {
    font-size: 20px;
  }
`;
