import React from "react";
import styled from "styled-components";
import Navbar from "../components/Navbar";
import Head from "next/head";
import ProjectContainer from "../components/ProjectContainer";
import thumbPaletter from "../public/paletter.png";
import thumbEcommerce from "../public/ecommerce.png";
import thumbNews from "../public/news.png";
import thumbTimer from "../public/timer.png";
import thumbWeather from "../public/weather.png";

const MainContainer = styled.main`
  min-width: 100vw;
  min-height: 100vh;
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  padding-left: 20%;
  padding-right: 20%;
  padding-top: 1rem;
  @media (max-width: 650px) {
    padding-left: 12%;
    padding-right: 12%;
  }
`;

const Title = styled.h1`
  font-size: 45px;
  font-family: DM Sans;
  font-weight: 600;
  color: white;
  @media (max-width: 500px) {
    font-size: 30px;
  }
`;

const Projects = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  @media (max-width: 650px) {
    padding: 0;
  }
`;

export default function projects() {
  return (
    <div
      style={{
        backgroundImage: "linear-gradient(to right, #222222 0%, black 100%)",
      }}
    >
      <Head>
        <title>Projetos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainContainer>
        <Title>Projetos</Title>
        <Projects>
          <ProjectContainer
            number={"01"}
            title={"Paletter"}
            url={"/projetos/paletter"}
            thumbnail={thumbPaletter}
            githubURL={"https://github.com/nardi00/paletter"}
            website={"https://nardi00.github.io/paletter/"}
          />
          <ProjectContainer
            number={"02"}
            title={"Recordrrr"}
            url={"/projetos/ecommerce"}
            thumbnail={thumbEcommerce}
            githubURL={"https://github.com/nardi00/shopping-cart"}
            website={"https://nardi00.github.io/shopping-cart/"}
          />
          <ProjectContainer
            number={"03"}
            title={"News"}
            url={"/projetos/news"}
            thumbnail={thumbNews}
            githubURL={"https://github.com/nardi00/news"}
            website={"https://nardi00.github.io/news/"}
          />
          <ProjectContainer
            number={"04"}
            title={"Timer widget"}
            url={"/projetos/timer"}
            thumbnail={thumbTimer}
            githubURL={"https://github.com/nardi00/electron-timer"}
            website={"https://github.com/nardi00/electron-timer"}
          />
          <ProjectContainer
            number={"05"}
            title={"Weather"}
            url={"/projetos/weather"}
            thumbnail={thumbWeather}
            githubURL={"https://github.com/nardi00/react-weather-app"}
            website={"https://nardi00.github.io/react-weather-app/"}
          />
        </Projects>
      </MainContainer>
    </div>
  );
}
